/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class principal extends javax.swing.JFrame {

    double v[];
    
    public principal() {
        initComponents();
        txtLongitud.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        cmdLlenadoManual = new javax.swing.JButton();
        cmdProductoria = new javax.swing.JButton();
        cmdSumatoria = new javax.swing.JButton();
        cmdLlenadoAutomatico = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();
        cmdMenorElemento = new javax.swing.JButton();
        cmdMayorElemento = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdMenorElemento1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos iniciales"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Longitud");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });
        jPanel2.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 90));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Ejercicio 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado "));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 90));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 240, 150));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdLlenadoManual.setText("Llenado Manual");
        cmdLlenadoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoManualActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenadoManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 32));

        cmdProductoria.setText("Productoria");
        cmdProductoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProductoriaActionPerformed(evt);
            }
        });
        jPanel4.add(cmdProductoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, 32));

        cmdSumatoria.setText("Sumatoria");
        cmdSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSumatoriaActionPerformed(evt);
            }
        });
        jPanel4.add(cmdSumatoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 32));

        cmdLlenadoAutomatico.setText("Llenado Automático");
        cmdLlenadoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoAutomaticoActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenadoAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 32));

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 32));

        cmdMenorElemento.setText("Menor Elemento");
        cmdMenorElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMenorElementoActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMenorElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, 32));

        cmdMayorElemento.setText("Mayor Elemento");
        cmdMayorElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMayorElementoActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMayorElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, 32));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 160, 300));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 40));

        cmdBorrar.setText("Nuevo");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 170, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 470));

        cmdMenorElemento1.setText("Menor Elemento");
        getContentPane().add(cmdMenorElemento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 140, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
    int longitud;
        if(txtLongitud.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE);
       txtLongitud.requestFocusInWindow();
       
        }   
      else if(Integer.parseInt(txtLongitud.getText().trim())==0){
      JOptionPane.showMessageDialog(this,"La longitud no puede ser 0","Error",JOptionPane.ERROR_MESSAGE); 
      txtLongitud.requestFocusInWindow();
      txtLongitud.selectAll();
   }
      else{
          longitud=Integer.parseInt(txtLongitud.getText().trim());
          v=new double[longitud];
          JOptionPane.showMessageDialog(this,"El vector ha sido creado exitoxamente");
 
          
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
    char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitudKeyTyped

    private void cmdLlenadoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoManualActionPerformed
double n;
  if(txtLongitud.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE); 
      txtLongitud.requestFocusInWindow();
      
   }
     else{ 
  for (int i=0; i<v.length; i++){
  n=Double.parseDouble(JOptionPane.showInputDialog(this,"Ingrese el elemento número "+(i+1)));
  v[i]=n;
   } 
 }
    }//GEN-LAST:event_cmdLlenadoManualActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
if(txtLongitud.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE);
       txtLongitud.requestFocusInWindow();
       
        }
else{
        for (int i=0 ; i<v.length ; i++){
    txtResultado.append(v[i]+"\n");
        }
}
        
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
    txtLongitud.setText(" ");
    txtResultado.setText(" ");
    v=null;
    txtLongitud.requestFocusInWindow();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdLlenadoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoAutomaticoActionPerformed
    double n, f;
    if(txtLongitud.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE);
       txtLongitud.requestFocusInWindow();
       
        }
    else{
        f= Double.parseDouble (JOptionPane.showInputDialog(this, "Digite el numero hasta donde quiere el llenado automatico "));
           while (f<v.length){
            JOptionPane.showMessageDialog(this, "Digite un numero mayor a : "+v.length);
            f= Double.parseDouble (JOptionPane.showInputDialog(this, "Digite el numero hasta donde quiere el llenado automatico "));
           }
        for (int i = 0; i < v.length; i++) {
            
        n=(int)(Math.random()*f + 1);  
        v[i]=n;
        }
      JOptionPane.showMessageDialog(this,"Vector llenado con éxito");  
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdLlenadoAutomaticoActionPerformed

    private void cmdSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSumatoriaActionPerformed
 double total=0;
  if(txtLongitud.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE);
       txtLongitud.requestFocusInWindow();
       
        }     
 else{ for (int i = 0; i < v.length; i++) {
           
            total=total+v[i];     
        }
    txtResultado.append("\nSumatoria: "+total);
         }    
    }//GEN-LAST:event_cmdSumatoriaActionPerformed

    private void cmdProductoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProductoriaActionPerformed
 double  producto=1;
 if(txtLongitud.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE);
       txtLongitud.requestFocusInWindow();
       
        }
 else{
        for (int i = 0; i < v.length; i++) {
           
           producto= (producto*v[i]);
        }
    txtResultado.append("\nProducto: "+producto);
 }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdProductoriaActionPerformed

    private void cmdMayorElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMayorElementoActionPerformed
    double mayor=0;
if(txtLongitud.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE);
       txtLongitud.requestFocusInWindow();      
        }
else{
    for (int i = 0; i < v.length; i++) {
            if (v[i]>mayor){
                mayor = v[i];
            }
       
 } 
     txtResultado.append("Número mayor: "+mayor);
}    // TODO add your handling code here:
    }//GEN-LAST:event_cmdMayorElementoActionPerformed

    private void cmdMenorElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMenorElementoActionPerformed
    double menor=9999999;
    if(txtLongitud.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(this,"Digite la longitud del vector","Error",JOptionPane.ERROR_MESSAGE);
       txtLongitud.requestFocusInWindow();
       
        }
    else{
      for (int i = 0; i < v.length; i++) {
            if (v[i]<menor){
                menor = v[i];
            }
    }
    txtResultado.append("\nNúmero menor : "+menor);  
  }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMenorElementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenadoAutomatico;
    private javax.swing.JButton cmdLlenadoManual;
    private javax.swing.JButton cmdMayorElemento;
    private javax.swing.JButton cmdMenorElemento;
    private javax.swing.JButton cmdMenorElemento1;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdProductoria;
    private javax.swing.JButton cmdSumatoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
